apiVersion: v1
kind: Pod
metadata:
  name: config-server-pod
  labels:
    app: config-server
spec:
  containers:
    - name: config-server
      image: igorsakhankov/config-server
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8888