name: Build Config Server Image and Push to ECR and Deploy to AWS App Runner

on:
  push:
    branches:
      - main
    paths:
      - 'config-server/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: config-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: everything

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image with bootBuildImage
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ./gradlew :config-server:bootBuildImage \
            --imageName=$IMAGE_URI

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to AWS App Runner
        run: |
          SERVICE_ARN=$(aws apprunner list-services \
            --query "ServiceSummaryList[?ServiceName=='config-server'].ServiceArn" \
            --output text)
          
          aws apprunner update-service \
            --service-arn $SERVICE_ARN \
            --source-configuration ImageRepositoryConfiguration="{ImageIdentifier=${{ env.IMAGE_URI }},ImageRepositoryType=ECR}" \
            --auto-deployments-enabled